redis:
  url: 'redis:6379' # Redis http address
ttl: 10 #TTL in second
reverse_proxy_url: 'http://traefik' # The reverse-proxy http address
regex:
  exclude: 'ARegexHere'
cache:
  mode: 'all' # By defautl it will use in-memory and redis third-party cache. It can be `all`, `redis` or `memory` declaration
  port:
    web: '80'
    tls: '443'
