FROM golang:1.12-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

ADD ./cmd /app/cmd
ADD ./*.go /app/src/souin/
ADD ./entrypoint.sh /app/src/souin/entrypoint.sh

WORKDIR /app/src/souin
ENV GOPATH /app
RUN go get .
RUN go install

EXPOSE 80

CMD ["sh", "./entrypoint.sh"]
