FROM golang:1.13-alpine

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc libc-dev

RUN mkdir -p /app/src/github.com/darkweak/cmd
RUN mkdir -p /ssl
RUN mkdir -p /app/src/github.com/darkweak/souin
ADD ./*.go /app/src/github.com/darkweak/souin/
ADD ./cache /app/src/github.com/darkweak/souin/cache
ADD ./errors /app/src/github.com/darkweak/souin/errors
ADD ./providers /app/src/github.com/darkweak/souin/providers
ADD ./default/server.* /app/src/github.com/darkweak/souin/
ADD ./entrypoint.sh /app/src/github.com/darkweak/souin/entrypoint.sh

WORKDIR /app/src/github.com/darkweak/souin
ENV GOPATH /app
ENV GOOS linux
ENV GOARCH arm
RUN go get ./...
RUN go get -u golang.org/x/lint/golint
RUN go install
RUN chmod 755 ./entrypoint.sh

EXPOSE 80

ENTRYPOINT ["./entrypoint.sh"]
