FROM golang:1.13-alpine AS souin

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc libc-dev
ENV GOPATH /app
RUN go get -u \
    golang.org/x/lint/golint \
    github.com/dgraph-io/ristretto \
    github.com/fsnotify/fsnotify \
    gopkg.in/yaml.v2

RUN mkdir -p /app/src/github.com/darkweak/souin
RUN mkdir -p /ssl
ADD ./*.go /app/src/github.com/darkweak/souin/
ADD ./cache /app/src/github.com/darkweak/souin/cache
ADD ./errors /app/src/github.com/darkweak/souin/errors
ADD ./providers /app/src/github.com/darkweak/souin/providers
ADD ./default/server.* /app/src/github.com/darkweak/souin/
ADD ./configuration/configuration.yml /
ADD ./configuration /app/src/github.com/darkweak/souin/configuration

WORKDIR /app/src/github.com/darkweak/souin

EXPOSE 80

CMD ["go", "run", "main.go"]
