[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.121.1"
HUGO_ENV = "production"

[[redirects]]
  from = "/"
  to = "/docs/"
  status = 301
  force = true