FROM golang:1.16-alpine AS development-runner

RUN apk update && apk upgrade && \
    apk add --no-cache bash git gcc libc-dev binutils-gold
ENV GOPATH /app
RUN mkdir -p /app/src/github.com/darkweak/souin/plugins/skipper


WORKDIR /app/src/github.com/darkweak/souin/plugins/skipper
COPY . .
RUN go mod tidy
RUN go mod download

CMD ["tail", "-f", "/dev/null"]
