FROM golang:1.18-alpine AS development-runner

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc libc-dev
ENV GOPATH /app
RUN mkdir -p /app/src/github.com/darkweak/souin
WORKDIR /app/src/github.com/darkweak/souin
COPY . .

WORKDIR /app/src/github.com/darkweak/souin/plugins/skipper
RUN go mod tidy
RUN go mod download

CMD ["go", "run", "examples/main.go"]
