FROM golang:1.19-alpine AS development-runner

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh gcc libc-dev
ENV GOPATH /app
RUN mkdir -p /app/src/github.com/darkweak/souin
WORKDIR /app/src/github.com/darkweak/souin
COPY . .

WORKDIR /app/src/github.com/darkweak/souin/plugins/beego
RUN go mod tidy
RUN go mod download

WORKDIR /app/src/github.com/darkweak/souin/plugins/beego/examples

CMD ["go", "run", "main.go"]
