// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/darkweak/souin/plugins/go-zero/examples/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:p",
				Handler: mainHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/souin-api/:apis",
				Handler: souin_apiHandler(serverCtx),
			},
		},
	)
}
