FROM ghcr.io/roadrunner-server/velox:latest as velox

ARG GH_TOKEN
ENV CGO_ENABLED=0
ENV VERSION=v2.10.7
ENV TIME="$(date +%H:%M)"

COPY plugins/roadrunner/examples/configuration.toml .
COPY . /opt
RUN sed -i "s/GH_TOKEN/${GH_TOKEN}/" configuration.toml

RUN vx build -c configuration.toml -o /usr/bin/

FROM composer:latest AS development-runner
COPY --from=velox /usr/bin/rr /usr/bin/rr

RUN docker-php-ext-install sockets
RUN composer require spiral/roadrunner nyholm/psr7

COPY plugins/roadrunner/examples .

CMD ["/usr/bin/rr", "serve"]
