@startuml
actor User
actor System
activate System
participant Souin
participant Memory
participant ReverseProxy
System -> ReverseProxy ++ : run()
System -> Souin ++ : main()
Souin -> Memory ++ : MemoryConnectionFactory()
Souin <-- Memory : AbstractProvider
... Waiting for user request ...
loop User requests
  User -> Souin : request
  activate User
  Souin -> Memory: GetRequestInCache()
  Souin <-- Memory: *Response
  group if the response from cache is not valid
    Souin -> ReverseProxy: GetRequestInReverseProxy()
    Souin <-- ReverseProxy: *Response
    Souin -> Memory: SetRequestInCache()
  end
Souin -> User : response
deactivate User
end
@enduml
