@startuml
actor User
actor System
participant Souin
collections Providers
participant Memory
participant Redis
participant ReverseProxy
System -> ReverseProxy ++ : run()
System -> Souin ++ : main()
Souin -> Providers : Init()
Providers -> Memory ++ : MemoryConnectionFactory()
Providers <-- Memory : *AbstractProvider
Providers -> Redis ++ : RedisConnectionFactory()
Providers <-- Redis : *AbstractProvider
Souin <-- Providers : AbstractProvider[]
loop User requests
  User -> Souin : request
  par Request providers content
    Souin -> Memory: GetRequestInCache()
  else
    Souin -> Redis: GetRequestInCache()
  else
    Souin -> ReverseProxy: GetRequestInReverseProxy()
  end
  par Response providers content
    Souin <-- Memory: *Response
  else
    Souin <-- Redis: *Response
  else
    Souin <-- ReverseProxy: *Response
    Souin -> Memory: SetRequestInCache()
    Souin -> Redis: SetRequestInCache()
  end
Souin -> User : response
end
@enduml
